server:
  port: 80
spring:
  datasource:
    dynamic:
      seata: true
      seataMode: AT
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://mysql:3306/demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true
          username: '{cipher}AQBvrGAsqP55DH3mYYKclu4bjm8lI+wIP4DLStBevqvYqn6EXi7bVwlFC6C5GsvgyhQsFC+KCLt/6qOGdUkFz13rniZDXSxf8IZIX50TTJZwCmcNwApx6rUWxfBcwnB4MYwfyysSrXaYa1bGQ+4z9X6NpE0q+u/Ba2oVYOO/ItM7AQA6C62d8bb9OGt+zNQanKWJ9L0Zg3cU5A9ls9MAI2xCewEDCcXFwNPNupJm0gjWoJwKwVPGk8iMGxOX/MrVOxQxMhDLKAHDvQEn3gnere/XGy6HbD5u1hBVj1NJq+4v3sgY50bDiskyZ04/yctjFZ20257G/UPLbRO2KALc/37EvSmsGqlG0JWqrRhSArlCRGpUXTtMr357Q5KaBlhw7Ac='
          password: '{cipher}AQAVXPre+rCg909IxzrH9XBw0STKs0nXq4k0Vh49j7Sy2+fHsumL++yzgCRln7wEAGAU+lD/8ecCGqWe68d5k8XF7k4Z7dKEVYq7cpPZdcHmYM8dusZCVXgTw0vD8I86eXnURzqCLVK4IWZicQM8DXDzPUFC88P1GG3Y3fQCwc7aHxhhAO0i7t+Mig8f8+Cj2iKeE8q3fT1ssUNnTZx7sxxr0De5a04tLzd5N9nikhzpGlElvYczKYPXs3y3ad9hT4B7YarN2GYV5TgR01I10ojpYUinRES/CaUGbQtGl7ypVaTs0KNxpwCb43n0uyxK0BdFvc+p/7wITft6VQG8NSpRVok+pMEkuug3RU8nLJNocsm3Q2LbWRlj47pXXN7C+tQOmN7w4WLFPxbjxUnFtlEO'
          driver-class-name: com.mysql.cj.jdbc.Driver
        postgres:
          url: jdbc:postgresql://postgres:5432/demo
          username: '{cipher}AQBoFo2LZI9ON3WNXmvm6UY56JxqNPLyTF8nPWQF2Cf6Oz8lx5U9OuJ/zzdfbso/0ahF+sdDQUF+JidHZGncgTnBSCErOz/b6sm/pGjZN2cFKNH9CFcxgGlZcETi0m5H8HIIrNf3WRbtRrOLPTUup4vTjVlYgpXkLaZRV/PcQiAHImpFOSlTRiUjMqNqlfk9Br5S52xyPLYKVo77VmdqpHwTISYKkT1TP9LflQfubMwaEC6gxN+bIR7DXh6zdFg3bvoHq5+zu+w99JapwUSniiemjqFakSQTgPsuAUx6zTNCZlwlGUbqGeSBGsPCFW3rX4mtG0Wc+/JvoAyWItxFipQPy0XmOunDb4dm04+z36pSzSBmkpaRNo67klnAMXlQQus='
          password: '{cipher}AQCf2bGDwelWRToHsAk7iY+Tm2ML2N6Smwhzuahcny/ZrcZmrr9B6TL5/1ABf+oUAFlxEjp/r3LSI2dVWFmVsE34GbEWlmJeiVzDingk+BCcazivDVMlSnMwRaNFd5WPRRH/MfqrH/EY3oTi5C700lDXy1PmXE8D6tLzzedcELY8S0THELPwUPM/3IVk/KTOee9KQneMzsUZtHCYcuD015fHv3c5GXPtvPUN2gl0ZTPrdks5Oil7y4uslhwfA1b/qjIHS3H6AB5lee+fM5wUrMaUlQQfQh5U9MjCXOvEEHYRxjHfluzFv5/mqFuhxfhT0V3u5Hc9gX4uN9VD9Nx5ZAjKHuzp/LSAbnBJJYduqEA/ffIWInauIRX2RxbLk6eclur8Jr5sSb/hNRT2cy7Y0BpO'
          driver-class-name: org.postgresql.Driver