server:
  port: 8001
spring:
  datasource:
    dynamic:
      seata: true
      seataMode: AT
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://renlm.cn:30306/demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true
          username: '{cipher}AQCMSr/ri9g0QUDsFqz2yiGMI9p9amILLK99GZr4hg4Ai+upy0YNmbn2V+frx9jOnR7xiOAxSBgPPtLwrLbCUMVmhVBDFd7rHUdOSE5Hyx3UEx7Ib76+9ok2HB4fJb8I2m7PjXetIzBOqH/4EtJKxCjcZzOvB9fkFXNnQ+h6rK7HmEJykvhsm6pCOm13oJ9jg0t+hCDcz11jATzUA4jW3w1ijUy8RelNh3Kt2ZgOt5+fmrJrFvBXK+BzZJmxzbwLhfkM4VBqiqS1mqMt2O34LHdAGYLl8LV/5DIk/ldfZBwxnLoGg7bWHOC7yxfHJ/SZJBHwnaHeC+F0/kKyOGfpZjf01AOCeoKBkaTn/NN3cahNYiZb0r1E7ZmHtNOA5Av9O5g='
          password: '{cipher}AQCJLXAmWvujVJ5PooUtA8XZ+26Os6ayAnXba9Sr2KFfIbYa+beU58tZekuGbgI3C+JYBqH1eqtuQhCL3Y2kVszVKRpZlh0Acj2AMBGDZgnnsFZtF3hYk8Ic72qqMrI0YO8TrfFRJmtkOC8+wNdh1/YX+nyZVm2u+lYBKUahVGJ7XEys59peGj6rR4ddZswcvnMskNcbsgnPHtGuq+YTgkW6NnlYo1b8HCFaqMURf2aadTZCstHBYTc2w40//0dvoSDz/SbsTpQvvP5tmQWPz/xmGNoiIGWE6tFQ200VN9tnaErP95TpDwzoY8l6Iz6d6Zt2QJ/Q8fiMs4Bd8JbEwoCUxTzewdXC+70ZKz5Fv1yFXRc6QkEsgeVn+S/YJyG9q633Ci/5v1KVekloFlGZwS7j'
          driverClassName: com.mysql.cj.jdbc.Driver
          init:
            schema: classpath:db/mysql/schema.sql
            data: classpath:db/mysql/data.sql
            continueOnError: false
            separator: ;
        postgres:
          url: jdbc:postgresql://renlm.cn:30432/demo
          username: '{cipher}AQBuDpc5BMrI7dUOMz1nuXc0/YfevtVp+zmzXjyqYadvdRx/IAXIq61lTI4TTvqEdL3Rm6DHyc+UGjRcT/+i3Yuuy3BFDe0afajg4zzaWf/bCngDIM64ldtgzPssdtV3/koex0M8wdvrUpBQ2tHdT4msIBZpG95XFQCRKDdFjkwJYh4EwC2Q8ahHgF97oS3bnMH57oWhu+6M2ZyBp/hHqBkHB32bdKYg8J5lYelF5m88owEnG/NrB87Pc3McMcRrsHEMfoYkobysdQ7UdfzHL0AYbAqlEkOhaDSABxuiWeFf3u2M26IiSMEYvUCOTCH+s9u+TxQ+u1GK1CQKS7NzVZG01+65dniWvE8LwLNWYCGhWMf7OhVij1uoK0BC/SDFdug='
          password: '{cipher}AQAcRVRjJEMrsQRcOcSup/SvQJlQ4AUhIUCJfiu6WgyWttl306QXgOfF7SmOV5EAFN0a97BBMMNH6A40reeCZeK0LwTvZj4zrfMtjNOFMhNrNyEfqTWOOdubFTW3gOJjXJVXSWXIHZ28l/aWPNIOVtKGk6GbXNkgDvRdzY7pO450OT5/UkEuk0bQeM+YlBJ+TsEdUoLVEjynMETBeLrlGYaAgdLq7AYMv/FkWSROsyOBIvAIftildxbXCWPrbxGfZsD4F632DuTHCUkNP2Yx6PbBWmRQ0VYkyun99ySE41hYwWa1tsX2Ufm5GxPX6cX7FPFceof0t1Yun00XQGufZ9o6pnuLXs2T5gpx45OrDCAZOKzeAqIV+zEtmVeqEjxTyY7b+Q561a6eb69feLy90BAC'
          driverClassName: org.postgresql.Driver
          init:
            schema: classpath:db/postgres/schema.sql
            data: classpath:db/postgres/data.sql
            continueOnError: false
            separator: ;