server:
  port: 7001
  servlet:
    session:
      cookie:
        name: EUREKA-SERVER
spring:
  security:
    user:
      name: springCloud
      password: 123654
eureka:
  datacenter: default
  environment: dev
  instance:
    preferIpAddress: false
    hostname: localhost
    nonSecurePort: ${server.port}
    instanceId: ${eureka.instance.hostname}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka