server:
  port: 7001
  servlet:
    session:
      cookie:
        name: EUREKA-SERVER
spring:
  security:
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PASSWORD}
  redis:
    clientName: eureka-server-prod
  session:
    redis:
      namespace: eurekaserver:session
eureka:
  datacenter: cloud
  environment: product
  instance:
    preferIpAddress: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    nonSecurePort: ${server.port}
    instanceId: ${eureka.instance.hostname}:${eureka.instance.nonSecurePort}
  client:
    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${FETCH_REGISTRY:false}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}