server:
  port: 7001
spring:
  security:
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PASSWORD}
  redis:
    host: "{cipher}AQBI1l5uTuz5P2C+B5yVyglh22dQ69WcGvyuBotNFsQOe5st4d4QVyMCdlj/WzY02jzQ0AedXyUVEXWRzhkjUWM7o4wfGwZiztKx0621anPzIBpiliZQVj4Gc5WzbTR54Pxy2LCnjgHjff4gzueLJc2GbRTtFjL8esiMMSqJBfdszuIdYlx1JfLDTCSMP9nJ8U4Y7WcolJcSkuo/cFWeYPKfz/vCDvaNCwnyxRMexGmA7L1LifIgKKn7lwXnFr0eb6AatqbJZ3UU2AbBjfePZMaaP7yeS7bt5Qyg6SeVuRo3minnnTE1KFdQHv0VEvqqlgcRr7rcJsQJEC8pO1mCP10Aae5FdaduXb2Zhy4BUaviQoSax9XPavYKXNLXBtDuOEY="
    port: "{cipher}AQArf3e3kNjk8mYg+R+JZi6qntnJqsXDxnxleb43jy3LiFg//5PV58NHs44huCF4TockkrHvdXge0s44RTPwkXyjXZl6CkEVJii3vjl3DkRj3fwI4c41aRpWalRFaKstotdWghK7oYrIWK5pG93yXylbeorL47L67sd6d+eIRs+QrAeS5jCX/YirqXeLcrDUd26qkEilUjLUf5MmHh7WVleN679yQva7Zv1yiTVge2QOGf2GfaL/YuQQilM37h3hkxYa6leUPjY6j01yAAgZ6+6mLITx2BsmESpJEJnwBZGDl6ohcs/2V2YW1nsfGVqpm62V8jS4giTJewp/e4L8oqiW8msDHotYa07frtk3D5AdLlOfNcIGgfAmtCQVK4E56KM="
    timeout: 6000
    password: "{cipher}AQAaba5srv3ik0bkgGETZjrSdnsE81EPYPIIoWMPEDW0r/UHDjin4N3iZJ1CFWVLUV25XA82Fnk+rVInu/3gJKt5yYbKxifYwMMboLp4MSrW+eT+PXNgNf1E1tOrf/bePtiTGIWLCruncRXkXs2p7md069ZlMUqB38WtmI+BxHMsBywqdo+LZaf8mX4742ZwjXx3jI3IJQbVUjyQZfX9RcEY25yLPgvS8Jp0npVTOeS9khKNj0TACMm9AVPpN6GhcDf3am879UreC0RsMp1QmdZgc9Yd24GjcQBr7CH7HjGIJUTrgrm9rwwqQUeiZBMfYpsUYu7XKSvdrBOeoe7Vu3wk+mflBLnYZAMvFlLdhhent1Mh0OAGhE0firlWbiLRHboFu9z2aUu2evBTdC1ccJS1DUe20majJnMeG1ThPM/7ng=="
    database: 7
    clientName: "{cipher}AQCXpCAi/ISGpDxFfPmsMQvJxNAD0cYhTBHWy744jmb4gSptdi6YjDOr71e05SUyonb05zFU3uPTjF2n8gQMOR1CLHIkANQ5QLAWWNLjohMvSANFnh/M3rHcNyJkK4T1H1rgd+daP9s3av0N7Z7YfATPwMr1OGaOrIL4Ds0/ulo7VzNeU9XOGh2bV0WGGPyfFOIu/II9eBjBv61vql46jwr5N115mxZMvId1n7rvpeWdYWbNiRRJ7ypKVSrEPmJIqjNPFrcuz8xMoxuGk8qcqkyReKjOgzkQyh785pSgRN/UDSN7j5cwDtLwXoOsqlMnXSqOYt/cPSflJfyz8g/7Mxrjo+baD3ELgIpgoTgV/hpeZHH5RbLo9xaggE6lomEDcVue1+yX2SojO5cEO2FdqMcM"
eureka:
  datacenter: cloud
  environment: product
  instance:
    preferIpAddress: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    nonSecurePort: ${server.port}
    instanceId: ${eureka.instance.hostname}:${eureka.instance.nonSecurePort}
  client:
    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${FETCH_REGISTRY:false}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}