server:
  port: 7002
  reactive:
    session:
      cookie:
        name: GATEWAY
security:
  ignore:
    whites:
    - /npmmirror
spring:
  cloud:
    gateway:
      defaultFilters:
      - TokenRelay
      globalcors:
        addToSimpleUrlHandlerMapping: true
        corsConfigurations:
          '[/npmmirror/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods: '*'
            allowCredentials: true
      routes:
      - id: baidu
        uri: no://op
        predicates:
        - Path=/baidu/**
        filters:
        - RedirectTo=302, https://www.baidu.com
      - id: npmmirror
        uri: https://registry.npmmirror.com
        predicates:
        - Path=/npmmirror/**
        filters:
        - StripPrefix=1