server:
  port: 7002
  reactive:
    session:
      cookie:
        name: GATEWAY
spring:
  redis:
    clientName: gateway-dev
  session:
    redis:
      namespace: gateway:session
  cloud:
    gateway:
      routes:
      - id: npmmirror
        uri: https://registry.npmmirror.com
        predicates:
        - Path=/npmmirror/**
        filters:
        - StripPrefix=1