server:
  port: 7002
  reactive:
    session:
      cookie:
        name: GATEWAY
spring:
  cloud:
    gateway:
      defaultFilters:
      - TokenRelay
      routes:
      - id: baidu
        uri: no://op
        predicates:
        - Path=/baidu/**
        filters:
        - RedirectTo=302, https://www.baidu.com
      - id: npmmirror
        uri: https://registry.npmmirror.com
        predicates:
        - Path=/npmmirror/**
        filters:
        - StripPrefix=1