server:
  port: 80
  reactive:
    session:
      cookie:
        name: GATEWAY
security:
  ignore:
    whites:
    - /config/monitor
    - /demo/**
spring:
  cloud:
    gateway:
      defaultFilters:
      - TokenRelay
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        addToSimpleUrlHandlerMapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
            - https://renlm.cn
            - https://mygraph.renlm.cn
            - https://auth-server.renlm.cn
            - https://gateway.renlm.cn
            allowedMethods:
            - GET
            - POST
      routes:
      - id: EurekaServer
        uri: lb://eureka-server
        predicates:
        - Path=/eureka
        filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 3
            redis-rate-limiter.burstCapacity: 5
            redis-rate-limiter.requestedTokens: 1
      - id: EurekaStatic
        uri: lb://eureka-server
        predicates:
        - Path=/eureka/js/**,/eureka/css/**,/eureka/fonts/**,/eureka/images/**
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 6
            redis-rate-limiter.burstCapacity: 10
            redis-rate-limiter.requestedTokens: 1
      - id: Config
        uri: lb://config-server
        predicates:
        - Path=/config/monitor
        filters:
        - StripPrefix=1
      - id: Demo
        uri: lb://demo
        predicates:
        - Path=/demo/**
        filters:
        - StripPrefix=1