server:
  port: 7002
  reactive:
    session:
      cookie:
        name: GATEWAY
security:
  ignore:
    whites:
    - /actuator/prometheus
    - /npmmirror
spring:
  cloud:
    gateway:
      defaultFilters:
      - TokenRelay
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        addToSimpleUrlHandlerMapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
            - http://127.0.0.1:3000
            allowedMethods:
            - GET
            - POST
      routes:
      - id: baidu
        uri: no://op
        predicates:
        - Path=/baidu/**
        filters:
        - RedirectTo=302, https://www.baidu.com
      - id: npmmirror
        uri: https://registry.npmmirror.com
        predicates:
        - Path=/npmmirror/**
        filters:
        - StripPrefix=1