server:
  port: 7002
  reactive:
    session:
      cookie:
        name: GATEWAY
spring:
  cloud:
    gateway:
      defaultFilters:
      - TokenRelay
      routes:
      - id: npmmirror
        uri: https://registry.npmmirror.com
        predicates:
        - Path=/npmmirror/**
        filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 2
            redis-rate-limiter.requestedTokens: 1