server:
  port: 7002
  servlet:
    session:
      storeType: redis
      cookie:
        name: GSESSIONID
      redis:
        flushMode: on_save
        namespace: gateway:session
spring:
  redis:
    host: '{cipher}AQBI1l5uTuz5P2C+B5yVyglh22dQ69WcGvyuBotNFsQOe5st4d4QVyMCdlj/WzY02jzQ0AedXyUVEXWRzhkjUWM7o4wfGwZiztKx0621anPzIBpiliZQVj4Gc5WzbTR54Pxy2LCnjgHjff4gzueLJc2GbRTtFjL8esiMMSqJBfdszuIdYlx1JfLDTCSMP9nJ8U4Y7WcolJcSkuo/cFWeYPKfz/vCDvaNCwnyxRMexGmA7L1LifIgKKn7lwXnFr0eb6AatqbJZ3UU2AbBjfePZMaaP7yeS7bt5Qyg6SeVuRo3minnnTE1KFdQHv0VEvqqlgcRr7rcJsQJEC8pO1mCP10Aae5FdaduXb2Zhy4BUaviQoSax9XPavYKXNLXBtDuOEY='
    port: '{cipher}AQArf3e3kNjk8mYg+R+JZi6qntnJqsXDxnxleb43jy3LiFg//5PV58NHs44huCF4TockkrHvdXge0s44RTPwkXyjXZl6CkEVJii3vjl3DkRj3fwI4c41aRpWalRFaKstotdWghK7oYrIWK5pG93yXylbeorL47L67sd6d+eIRs+QrAeS5jCX/YirqXeLcrDUd26qkEilUjLUf5MmHh7WVleN679yQva7Zv1yiTVge2QOGf2GfaL/YuQQilM37h3hkxYa6leUPjY6j01yAAgZ6+6mLITx2BsmESpJEJnwBZGDl6ohcs/2V2YW1nsfGVqpm62V8jS4giTJewp/e4L8oqiW8msDHotYa07frtk3D5AdLlOfNcIGgfAmtCQVK4E56KM='
    timeout: 6000
    password: '{cipher}AQAaba5srv3ik0bkgGETZjrSdnsE81EPYPIIoWMPEDW0r/UHDjin4N3iZJ1CFWVLUV25XA82Fnk+rVInu/3gJKt5yYbKxifYwMMboLp4MSrW+eT+PXNgNf1E1tOrf/bePtiTGIWLCruncRXkXs2p7md069ZlMUqB38WtmI+BxHMsBywqdo+LZaf8mX4742ZwjXx3jI3IJQbVUjyQZfX9RcEY25yLPgvS8Jp0npVTOeS9khKNj0TACMm9AVPpN6GhcDf3am879UreC0RsMp1QmdZgc9Yd24GjcQBr7CH7HjGIJUTrgrm9rwwqQUeiZBMfYpsUYu7XKSvdrBOeoe7Vu3wk+mflBLnYZAMvFlLdhhent1Mh0OAGhE0firlWbiLRHboFu9z2aUu2evBTdC1ccJS1DUe20majJnMeG1ThPM/7ng=='
    database: 8
    clientName: '{cipher}AQAeaogXspDLWSHklXBYAma4iWkUDMjJhNyZPrSX3hYkF06uubsw9ypmQ8BAJ8sxKpviZGkv5jicT6wQn2ZKEBzRKucKQqRjaCnAfbBznpwX5Ea2umzFynpddd/yHPR4IWyMwMhxKcBUcweC9aMDSjT8x4f1UhM6bC14waCFxV6TTBkJHWRvngrSAjNTuaJVYwFkpHeXrWAOLVFSWbOnRfitWGSpjuLtKc0dQBftb8Z4Fco43oZWPmcUMCOjCiZhs7eW1iK2aJVZVgHkqFZDl3lCUemhz7w46t/SXlgHEl0RRssmsl2K6p5o2PAYvwrt/p2SLCX0o7Yh3cTKp4xpJl95ehomFqCWYjojDusXWtwdbDQc0bH0dN4bSoBke6O7xuX4DI/oEuMnseUZAiCFy8nO'
  security:
    oauth2:
      client:
        registration:
          messaging-gateway-oidc:
            provider: gateway-client-provider
            client-id: relive-client
            client-secret: relive-client
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
            - openid
            - profile
            client-name: messaging-client
        provider:
          gateway-client-provider:
            authorization-uri: http://127.0.0.1:8080/oauth2/authorize
            token-uri: http://127.0.0.1:8080/oauth2/token
            jwk-set-uri: http://127.0.0.1:8080/oauth2/jwks
            user-info-uri: http://127.0.0.1:8080/userinfo
            user-name-attribute: sub
  cloud:
    gateway:
      routes:
      - id: npmmirror
        uri: https://registry.npmmirror.com
        predicates:
        - Path=/npmmirror/**
        filters:
        - StripPrefix=1