server:
  port: 80
  reactive:
    session:
      cookie:
        name: GATEWAY
spring:
  cloud:
    gateway:
      defaultFilters:
      - TokenRelay
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        addToSimpleUrlHandlerMapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
            - https://renlm.cn
            allowedMethods:
            - GET
            - POST
      routes:
      - id: EurekaServer
        uri: lb://eureka-server
        predicates:
        - Path=/eureka
        filters:
        - StripPrefix=1
      - id: EurekaStatic
        uri: lb://eureka-server
        predicates:
        - Path=/eureka/js/**,/eureka/css/**,/eureka/fonts/**,/eureka/images/**
      - id: Config
        uri: lb://config-server
        predicates:
        - Path=/config/monitor
        filters:
        - StripPrefix=1
      - id: Demo
        uri: lb://demo
        predicates:
        - Path=/demo/**
        filters:
        - StripPrefix=1