server:
  port: 7002
  reactive:
    session:
      cookie:
        name: GATEWAY
spring:
  cloud:
    gateway:
      defaultFilters:
      - TokenRelay
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        addToSimpleUrlHandlerMapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
            - https://renlm.cn
            allowedMethods:
            - GET
            - POST
      routes:
      - id: EurekaServer
        uri: lb://eureka-server:7001
        predicates:
        - Path=/eureka
        filters:
        - StripPrefix=1
      - id: EurekaStatic
        uri: lb://eureka-server:7001
        predicates:
        - Path=/eureka/{js|css|fonts|images}/**