server:
  port: 7002
security:
  oauth2:
    client:
      clientId: 89630a412fa314777dc2
      clientSecret: c7a29ec26ec7805e78b496ea67cc13e5a9b8bcf0
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false
spring:
  cloud:
    gateway:
      routes:
      - id: npmmirror
        uri: https://registry.npmmirror.com
        predicates:
        - Path=/npmmirror/**
        filters:
        - StripPrefix=1