server:
  port: 7002
  reactive:
    session:
      cookie:
        name: GATEWAY
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://127.0.0.1:8080
  cloud:
    gateway:
      routes:
      - id: npmmirror
        uri: https://registry.npmmirror.com
        predicates:
        - Path=/npmmirror/**
        filters:
        - StripPrefix=1