spring:
  security:
    oauth2:
      resourceserver:
        opaqueToken:
          clientId: otDev
          clientSecret: secretOtDev
          introspectionUri: http://127.0.0.1:8080/oauth2/introspect