spring:
  security:
    oauth2:
      resourceserver:
        opaqueToken:
          clientId: otProd
          clientSecret: secretOtProd
          introspectionUri: https://auth-server.renlm.cn/oauth2/introspect