spring:
  security:
    oauth2:
      resourceserver:
        opaqueToken:
          clientId: otDev
          clientSecret: secretOtDev
          introspectionUri: http://localhost/mygraph/oauth2/introspect