spring:
  security:
    oauth2:
      resourceserver:
        opaqueToken:
          clientId: otProd
          clientSecret: secretOtProd
          introspectionUri: https://mygraph.renlm.cn/oauth2/introspect